routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');

Route::get('/auth/register', [App\Http\Controllers\AuthController::class, 'registerForm'])->name('auth.register_form');
Route::post('/auth/register', [App\Http\Controllers\AuthController::class, 'register'])->name('auth.register');

Route::get('/auth/login', [App\Http\Controllers\AuthController::class, 'loginForm'])->name('auth.login_form');
Route::post('/auth/login', [App\Http\Controllers\AuthController::class, 'login'])->name('auth.login');
Route::post('/auth/logout', [App\Http\Controllers\AuthController::class, 'logout'])->name('auth.logout');

Route::get('categories', [App\Http\Controllers\CategoryController::class, 'index'])->name('categories.list');
Route::get('categories/create', [App\Http\Controllers\CategoryController::class, 'create'])->name('categories.create');
Route::post('categories/store', [App\Http\Controllers\CategoryController::class, 'store'])->name('categories.store');
Route::get('categories/{category}/edit', [App\Http\Controllers\CategoryController::class, 'edit'])->name('categories.edit');
Route::put('categories/{category}/update', [App\Http\Controllers\CategoryController::class, 'update'])->name('categories.update');
Route::delete('categories/{category}/delete', [App\Http\Controllers\CategoryController::class, 'delete'])->name('categories.delete');

Route::resource('posts', App\Http\Controllers\PostController::class);

//Auth::routes();

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['category_id', 'title', 'content', 'user_id'];

    public function category() {
        return $this->belongsTo(category::class);
    }

    public function author() {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use PhpParser\Node\Expr\FuncCall;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'role',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [];

    public function getFullNameAttribute() {
        return $this->last_name . ' ' . $this->first_name;
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\Category;

class PostController extends Controller
{
    public function index()
    {
        $posts = Post::get();
        return view('posts.index', [
            'posts' => $posts
        ]);
    }

    public function create()
    {
        if (Auth::user()->role !== 'admin') {
            return redirect(route('home'));
        }
        $categories = Category::get();
        return view('posts.create', [
            'categories' => $categories
        ]);
    }

    public function store(Request $request)
    {
        if (Auth::user()->role !== 'admin') {
            return redirect(route('home'));
        }
        $input = $request->all();
        $input['user_id'] = Auth::id();
        Post::create($input);
        return redirect(route('posts.index'));
    }

    public function edit(Post $post)
    {
        if (Auth::user()->role !== 'admin') {
            return redirect(route('home'));
        }
        $categories = Category::pluck('name', 'id');
        return view('posts.edit', [
            'categories' => $categories,
            'post' => $post
        ]);
    }

    public function update(Request $request, Post $post)
    {
        if (Auth::user()->role !== 'admin') {
            return redirect(route('home'));
        }
        $post->title = $request->get('title');
        $post->content = $request->get('content');
        $post->save();
        return redirect(route('posts.index'));
    }

    public function destroy(Post $post)
    {
        if (Auth::user()->role !== 'admin') {
            return redirect(route('home'));
        }
        $post->delete();
        return redirect(route('posts.index'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">New Post</h6>
        </div>
        <div class="card-body">
            <form action="{{ route('posts.store') }}" method="POST" class="user">
                @csrf
                <div class="form-group row">
                    <div class="col-sm-6">
                        <select required class="form-control form-control-user" name="category_id">
                            <option value="">Please select one</option>
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-6">
                        <input type="text" required class="form-control form-control-user" name="title" placeholder="Title">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-6">
                        <textarea required row="3" class="form-control form-control-user" name="content"></textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-primary btn-user btn-block">
                            Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit Post</h6>
        </div>
        <div class="card-body">
            <form action="{{ route('posts.update', $post->id) }}" method="POST" class="user">
                @csrf
                @method('put')


                <div class="form-group row">
                    <div class="col-sm-6">
                        <input type="text" required class="form-control form-control-user" name="title" placeholder="Post Name" value="{{ $post->title }}">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6">
                        <input type="text" required class="form-control form-control-user" name="content" placeholder="Post Content" value="{{ $post->content }}">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-primary btn-user btn-block">
                            Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Posts</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Category Name</th>
                            <th>Title</th>
                            <th>Content</th>
                            <th>Author</th>
                            @if(Auth::user()->role === 'admin')
                            <th>
                                <a href="{{ route('posts.create') }}" class="btn btn-primary">+ (New)</a>
                            </th>
                            @endif
                        </tr>
                    </thead>
                    
                    <tbody>
                        @foreach($posts as $post)
                            <tr>
                                <td>{{ $loop->index + 1 }}</td>
                                <td>{{ $post->category->name }}</td>
                                <td>{{ $post->title }}</td>
                                <td>{{ $post->content }}</td>
                                <td>{{ $post->author->full_name }}</td>
                                @if(Auth::user()->role === 'admin')
                                <td>
                                    <ul>
                                        <li>
                                            <a class="btn btn-primary" href="{{ route('posts.edit', $post->id) }}">Edit</a>
                                        </li>
                                        <li>
                                            <form action="{{ route('posts.destroy', $post->id) }}" method="POST">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </li>
                                    </ul>
                                </td>
                                @endif
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection